//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xWAREActivity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public System.Guid id { get; set; }
        public string text { get; set; }
        public System.Guid userid { get; set; }
        public System.Guid postid { get; set; }
        public System.DateTime insertiondate { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
